# Prepare visualization of the results

## Definitions

### Sensors

In [123]:
sensor_co_name = 'alpha_co_conc'
sensor_no2_name = 'alpha_no2_conc'
sensor_o3_name = 'alpha_o3_conc'
sensor_so2_name = 'alpha_so2_conc'
sensor_pm_10_name = 'alpha_pm_10_conc'

### Directories and paths

#### R2

In [124]:
output_directory_path = 'output/'
co_r2_file_name = output_directory_path + sensor_co_name + '_r2.csv'
no2_r2_file_name = output_directory_path + sensor_no2_name + '_r2.csv'
o3_r2_file_name = output_directory_path + sensor_o3_name + '_r2.csv'
so2_r2_file_name = output_directory_path + sensor_so2_name + '_r2.csv'
pm_10_r2_file_name = output_directory_path + sensor_pm_10_name + '_r2.csv'

#### RMSE

In [125]:
output_directory_path = 'output/'
co_rmse_file_name = output_directory_path + sensor_co_name + '_rmse.csv'
no2_rmse_file_name = output_directory_path + sensor_no2_name + '_rmse.csv'
o3_rmse_file_name = output_directory_path + sensor_o3_name + '_rmse.csv'
so2_rmse_file_name = output_directory_path + sensor_so2_name + '_rmse.csv'
pm_10_rmse_file_name = output_directory_path + sensor_pm_10_name + '_rmse.csv'

#### MAE

In [126]:
output_directory_path = 'output/'
co_mae_file_name = output_directory_path + sensor_co_name + '_mae.csv'
no2_mae_file_name = output_directory_path + sensor_no2_name + '_mae.csv'
o3_mae_file_name = output_directory_path + sensor_o3_name + '_mae.csv'
so2_mae_file_name = output_directory_path + sensor_so2_name + '_mae.csv'
pm_10_mae_file_name = output_directory_path + sensor_pm_10_name + '_mae.csv'

## Upload Results

In [127]:
def rename_sensors_names(new_name, old_names):
    names = [name.strip() for name in old_names.split('|')]
    new_names = ""
    for name in names:
        if name == 'measuring': 
            if len(new_names) > 0: new_names += " + "
            new_names += new_name
        if name == 'measuring 1': 
            if len(new_names) > 0: new_names += " + "
            new_names += (new_name + " \N{SUPERSCRIPT ONE}")
        if name == 'measuring 2': 
            if len(new_names) > 0: new_names += " + "
            new_names += (new_name + ' \N{SUPERSCRIPT TWO}')
        elif name == 'temperature': 
            if len(new_names) > 0: new_names += " + "
            new_names += 'T'
    return new_names

### CO

#### R2

In [128]:
import pandas as pd

co_r2_dataframe = (pd.read_csv(co_r2_file_name)
                .rename(columns={'Unnamed: 0': 'Sensores',
                                 'MLP Regression': 'MLP',
                                 'Multilinear Regression': 'MLR',
                                 'KNN Regression': 'KNN',
                                 'Random Forests Regression': 'RF'}))
co_r2_dataframe = co_r2_dataframe[~(co_r2_dataframe['Sensores'].str.contains("no Temp"))]
co_r2_dataframe['Sensores'] = (co_r2_dataframe['Sensores']
                            .apply(lambda names: rename_sensors_names(new_name='CO', 
                                                                      old_names=names)))
co_r2_dataframe

,Sensores,MLP,MLR,KNN,RF
0,CO,"{'Mean': -0.4705984769492099, 'Std': 0.5524013...","{'Mean': -0.5179069267174252, 'Std': 0.6266450...","{'Mean': -0.6085937814241431, 'Std': 0.5996664...","{'Mean': -0.6253347577905872, 'Std': 0.6137747..."
2,CO + T,"{'Mean': -0.6097272259213187, 'Std': 0.4784936...","{'Mean': -0.5225011588293411, 'Std': 0.6131616...","{'Mean': -0.5878941795521129, 'Std': 0.4224268...","{'Mean': -0.5753111026129333, 'Std': 0.4887827..."

#### RMSE

In [129]:
co_rmse_dataframe = (pd.read_csv(co_rmse_file_name)
                .rename(columns={'Unnamed: 0': 'Sensores',
                                 'MLP Regression': 'MLP',
                                 'Multilinear Regression': 'MLR',
                                 'KNN Regression': 'KNN',
                                 'Random Forests Regression': 'RF'}))
co_rmse_dataframe = co_rmse_dataframe[~(co_rmse_dataframe['Sensores'].str.contains("no Temp"))]
co_rmse_dataframe['Sensores'] = (co_rmse_dataframe['Sensores']
                            .apply(lambda names: rename_sensors_names(new_name='CO', 
                                                                      old_names=names)))
co_rmse_dataframe

,Sensores,MLP,MLR,KNN,RF
0,CO,"{'Mean': -0.06002105646272177, 'Std': 0.018415...","{'Mean': -0.06033176863665616, 'Std': 0.016760...","{'Mean': -0.06253326874677716, 'Std': 0.017685...","{'Mean': -0.0627292658271042, 'Std': 0.0173899..."
2,CO + T,"{'Mean': -0.06306786888633205, 'Std': 0.017199...","{'Mean': -0.06056940595908787, 'Std': 0.016785...","{'Mean': -0.06261468435202577, 'Std': 0.015735...","{'Mean': -0.06192626234098468, 'Std': 0.015608..."

#### MAE

In [130]:
co_mae_dataframe = (pd.read_csv(co_mae_file_name)
                .rename(columns={'Unnamed: 0': 'Sensores',
                                 'MLP Regression': 'MLP',
                                 'Multilinear Regression': 'MLR',
                                 'KNN Regression': 'KNN',
                                 'Random Forests Regression': 'RF'}))
co_mae_dataframe = co_mae_dataframe[~(co_mae_dataframe['Sensores'].str.contains("no Temp"))]
co_mae_dataframe['Sensores'] = (co_mae_dataframe['Sensores']
                            .apply(lambda names: rename_sensors_names(new_name='CO', 
                                                                      old_names=names)))
co_mae_dataframe

,Sensores,MLP,MLR,KNN,RF
0,CO,"{'Mean': -0.044355079466332485, 'Std': 0.01534...","{'Mean': -0.04536957612984312, 'Std': 0.013410...","{'Mean': -0.04674262781811754, 'Std': 0.014331...","{'Mean': -0.047046744498268955, 'Std': 0.01432..."
2,CO + T,"{'Mean': -0.0467181577198752, 'Std': 0.0118342...","{'Mean': -0.045572437789768994, 'Std': 0.01300...","{'Mean': -0.04654315058062059, 'Std': 0.011484...","{'Mean': -0.04610167576844994, 'Std': 0.012044..."

### NO2

#### R2

In [131]:
import pandas as pd

no2_r2_dataframe = (pd.read_csv(no2_r2_file_name)
                .rename(columns={'Unnamed: 0': 'Sensores',
                                 'MLP Regression': 'MLP',
                                 'Multilinear Regression': 'MLR',
                                 'KNN Regression': 'KNN',
                                 'Random Forests Regression': 'RF'}))
no2_r2_dataframe = no2_r2_dataframe[~(no2_r2_dataframe['Sensores'].str.contains("no Temp"))]
no2_r2_dataframe['Sensores'] = (no2_r2_dataframe['Sensores']
                            .apply(lambda names: rename_sensors_names(new_name='NO2', 
                                                                      old_names=names)))
no2_r2_dataframe

,Sensores,MLP,MLR,KNN,RF
0,NO2,"{'Mean': -5.284818462903211, 'Std': 7.51631457...","{'Mean': -4.223763345893145, 'Std': 6.14684164...","{'Mean': -4.774244724582815, 'Std': 6.46618190...","{'Mean': -6.180123049292353, 'Std': 8.35552237..."
1,NO2 + T,"{'Mean': -2.7991482510752306, 'Std': 3.5196573...","{'Mean': -4.249047894517364, 'Std': 5.94137911...","{'Mean': -2.921339481552441, 'Std': 3.87826537...","{'Mean': -3.389632719291054, 'Std': 4.58335675..."

#### RMSE

In [132]:
no2_rmse_dataframe = (pd.read_csv(no2_rmse_file_name)
                .rename(columns={'Unnamed: 0': 'Sensores',
                                 'MLP Regression': 'MLP',
                                 'Multilinear Regression': 'MLR',
                                 'KNN Regression': 'KNN',
                                 'Random Forests Regression': 'RF'}))
no2_rmse_dataframe = no2_rmse_dataframe[~(no2_rmse_dataframe['Sensores'].str.contains("no Temp"))]
no2_rmse_dataframe['Sensores'] = (no2_rmse_dataframe['Sensores']
                            .apply(lambda names: rename_sensors_names(new_name='NO2', 
                                                                      old_names=names)))
no2_rmse_dataframe

,Sensores,MLP,MLR,KNN,RF
0,NO2,"{'Mean': -13.181423370717184, 'Std': 3.9109842...","{'Mean': -12.837072202273356, 'Std': 3.9118573...","{'Mean': -13.09189747804711, 'Std': 3.77812867...","{'Mean': -14.141035572917861, 'Std': 3.7351763..."
1,NO2 + T,"{'Mean': -12.486890981254557, 'Std': 3.7691174...","{'Mean': -12.970798721899621, 'Std': 3.6596226...","{'Mean': -12.48824792927512, 'Std': 3.75787777...","{'Mean': -12.458303971614757, 'Std': 3.5079414..."

#### MAE

In [133]:
no2_mae_dataframe = (pd.read_csv(no2_mae_file_name)
                .rename(columns={'Unnamed: 0': 'Sensores',
                                 'MLP Regression': 'MLP',
                                 'Multilinear Regression': 'MLR',
                                 'KNN Regression': 'KNN',
                                 'Random Forests Regression': 'RF'}))
no2_mae_dataframe = no2_mae_dataframe[~(no2_mae_dataframe['Sensores'].str.contains("no Temp"))]
no2_mae_dataframe['Sensores'] = (no2_mae_dataframe['Sensores']
                            .apply(lambda names: rename_sensors_names(new_name='NO2', 
                                                                      old_names=names)))
no2_mae_dataframe

,Sensores,MLP,MLR,KNN,RF
0,NO2,"{'Mean': -10.213284777501293, 'Std': 2.3639002...","{'Mean': -9.902687472555082, 'Std': 1.86300117...","{'Mean': -10.087875132275133, 'Std': 2.0202562...","{'Mean': -10.801158898827351, 'Std': 2.3681370..."
1,NO2 + T,"{'Mean': -9.470028636453886, 'Std': 2.16992206...","{'Mean': -10.09430184713376, 'Std': 1.80514292...","{'Mean': -9.23922193323566, 'Std': 2.028367936...","{'Mean': -9.597202817297823, 'Std': 2.09481647..."

### O3

#### R2

In [134]:
import pandas as pd

o3_r2_dataframe = (pd.read_csv(o3_r2_file_name)
                .rename(columns={'Unnamed: 0': 'Sensores',
                                 'MLP Regression': 'MLP',
                                 'Multilinear Regression': 'MLR',
                                 'KNN Regression': 'KNN',
                                 'Random Forests Regression': 'RF'}))
o3_r2_dataframe = o3_r2_dataframe[~(o3_r2_dataframe['Sensores'].str.contains("no Temp"))]
o3_r2_dataframe['Sensores'] = (o3_r2_dataframe['Sensores']
                            .apply(lambda names: rename_sensors_names(new_name='O3', 
                                                                      old_names=names)))
o3_r2_dataframe

,Sensores,MLP,MLR,KNN,RF
0,O3 ¹,"{'Mean': -0.3590352987374866, 'Std': 0.4875467...","{'Mean': -0.31393866391228065, 'Std': 0.391778...","{'Mean': -0.381542208960577, 'Std': 0.37995180...","{'Mean': -0.4363041824845843, 'Std': 0.5436679..."
1,O3 ²,"{'Mean': 0.10778226186351789, 'Std': 0.4546295...","{'Mean': 0.06254640161102244, 'Std': 0.5076535...","{'Mean': 0.0344623683781361, 'Std': 0.53428288...","{'Mean': -0.03368810885029627, 'Std': 0.583356..."
4,O3 ¹ + O3 ²,"{'Mean': 0.24297738827564416, 'Std': 0.2937189...","{'Mean': 0.10769912755308204, 'Std': 0.4340426...","{'Mean': 0.1379729535573526, 'Std': 0.35003831...","{'Mean': 0.1666223103891742, 'Std': 0.32999712..."
6,O3 ¹ + T,"{'Mean': 0.40483185449395975, 'Std': 0.2939729...","{'Mean': 0.3219915543736644, 'Std': 0.36370439...","{'Mean': 0.3218157304923227, 'Std': 0.31969197...","{'Mean': 0.3422154928968856, 'Std': 0.33165177..."
8,O3 ² + T,"{'Mean': 0.27911067901007264, 'Std': 0.5833342...","{'Mean': 0.32537020254613175, 'Std': 0.5248155...","{'Mean': 0.18522158895486243, 'Std': 0.7950958...","{'Mean': 0.26864173121446866, 'Std': 0.5852008..."
12,O3 ¹ + O3 ² + T,"{'Mean': 0.29138923338695344, 'Std': 0.5448676...","{'Mean': 0.3249377596070171, 'Std': 0.49916134...","{'Mean': 0.22782756835896678, 'Std': 0.6564196...","{'Mean': 0.2797003936344725, 'Std': 0.52397884..."

#### RMSE

In [135]:
o3_rmse_dataframe = (pd.read_csv(o3_rmse_file_name)
                .rename(columns={'Unnamed: 0': 'Sensores',
                                 'MLP Regression': 'MLP',
                                 'Multilinear Regression': 'MLR',
                                 'KNN Regression': 'KNN',
                                 'Random Forests Regression': 'RF'}))
o3_rmse_dataframe = o3_rmse_dataframe[~(o3_rmse_dataframe['Sensores'].str.contains("no Temp"))]
o3_rmse_dataframe['Sensores'] = (o3_rmse_dataframe['Sensores']
                            .apply(lambda names: rename_sensors_names(new_name='O3', 
                                                                      old_names=names)))
o3_rmse_dataframe

,Sensores,MLP,MLR,KNN,RF
0,O3 ¹,"{'Mean': -16.16310463643958, 'Std': 4.15690987...","{'Mean': -16.075016608681626, 'Std': 4.2958590...","{'Mean': -16.537812856380086, 'Std': 4.8489591...","{'Mean': -16.49411614266595, 'Std': 3.98994872..."
1,O3 ²,"{'Mean': -12.75936925314807, 'Std': 3.12449888...","{'Mean': -13.073446438280016, 'Std': 3.2132043...","{'Mean': -13.134640368866243, 'Std': 3.1305355...","{'Mean': -13.537134462443422, 'Std': 3.0989666..."
4,O3 ¹ + O3 ²,"{'Mean': -11.844505168198667, 'Std': 2.6303738...","{'Mean': -12.695118880946264, 'Std': 2.6560693...","{'Mean': -12.580053136678202, 'Std': 2.6468034...","{'Mean': -12.405779957717936, 'Std': 2.7855572..."
6,O3 ¹ + T,"{'Mean': -10.548799746294886, 'Std': 2.6952564...","{'Mean': -11.038442870113439, 'Std': 2.4128327...","{'Mean': -11.21393333518993, 'Std': 2.70829079...","{'Mean': -11.081654783000369, 'Std': 2.8254130..."
8,O3 ² + T,"{'Mean': -11.242668597784663, 'Std': 3.5378469...","{'Mean': -10.839680124780415, 'Std': 2.8836038...","{'Mean': -11.576093831423885, 'Std': 3.5776048...","{'Mean': -11.31576386003575, 'Std': 3.33191994..."
12,O3 ¹ + O3 ² + T,"{'Mean': -11.1040078755053, 'Std': 3.196654090...","{'Mean': -10.815628801521443, 'Std': 2.6696342...","{'Mean': -11.352927024367883, 'Std': 3.0823109...","{'Mean': -11.228857207789419, 'Std': 2.9997274..."

#### MAE

In [136]:
o3_mae_dataframe = (pd.read_csv(o3_mae_file_name)
                .rename(columns={'Unnamed: 0': 'Sensores',
                                 'MLP Regression': 'MLP',
                                 'Multilinear Regression': 'MLR',
                                 'KNN Regression': 'KNN',
                                 'Random Forests Regression': 'RF'}))
o3_mae_dataframe = o3_mae_dataframe[~(o3_mae_dataframe['Sensores'].str.contains("no Temp"))]
o3_mae_dataframe['Sensores'] = (o3_mae_dataframe['Sensores']
                            .apply(lambda names: rename_sensors_names(new_name='O3', 
                                                                      old_names=names)))
o3_mae_dataframe

,Sensores,MLP,MLR,KNN,RF
0,O3 ¹,"{'Mean': -12.851934311563252, 'Std': 2.8943978...","{'Mean': -12.772964719496489, 'Std': 3.1342366...","{'Mean': -12.738954192592592, 'Std': 3.5552394...","{'Mean': -13.117565183582641, 'Std': 2.8028374..."
1,O3 ²,"{'Mean': -10.205505427194838, 'Std': 2.7249032...","{'Mean': -10.430261037583083, 'Std': 2.8036839...","{'Mean': -10.52120838888889, 'Std': 2.72747807...","{'Mean': -10.820106724525223, 'Std': 2.6934732..."
4,O3 ¹ + O3 ²,"{'Mean': -9.184334571540685, 'Std': 2.15423944...","{'Mean': -9.970277663184959, 'Std': 2.37601570...","{'Mean': -9.83580634920635, 'Std': 2.246529679...","{'Mean': -9.71966168653506, 'Std': 2.299398631..."
6,O3 ¹ + T,"{'Mean': -8.211013497910342, 'Std': 2.22502167...","{'Mean': -8.730173009248293, 'Std': 2.01824149...","{'Mean': -8.639379815873017, 'Std': 2.24517271...","{'Mean': -8.577830964884086, 'Std': 2.24000212..."
8,O3 ² + T,"{'Mean': -8.798120692747508, 'Std': 2.85301683...","{'Mean': -8.666600128680283, 'Std': 2.38459187...","{'Mean': -9.26748662786596, 'Std': 3.022855385...","{'Mean': -9.065828416936354, 'Std': 2.76261304..."
12,O3 ¹ + O3 ² + T,"{'Mean': -8.681200488443753, 'Std': 2.64973031...","{'Mean': -8.640193445577015, 'Std': 2.20988070...","{'Mean': -8.877125111437426, 'Std': 2.63713459...","{'Mean': -8.846975162563108, 'Std': 2.47772071..."

### SO2

#### R2

In [137]:
import pandas as pd

so2_r2_dataframe = (pd.read_csv(so2_r2_file_name)
                .rename(columns={'Unnamed: 0': 'Sensores',
                                 'MLP Regression': 'MLP',
                                 'Multilinear Regression': 'MLR',
                                 'KNN Regression': 'KNN',
                                 'Random Forests Regression': 'RF'}))
so2_r2_dataframe = so2_r2_dataframe[~(so2_r2_dataframe['Sensores'].str.contains("no Temp"))]
so2_r2_dataframe['Sensores'] = (so2_r2_dataframe['Sensores']
                            .apply(lambda names: rename_sensors_names(new_name='SO2', 
                                                                      old_names=names)))
so2_r2_dataframe

,Sensores,MLP,MLR,KNN,RF
0,SO2 ¹,"{'Mean': -8.714745678031061, 'Std': 19.8416050...","{'Mean': -6.944200704828846, 'Std': 17.2803403...","{'Mean': -31.960675281611902, 'Std': 79.299303...","{'Mean': -11.775195537651387, 'Std': 30.506392..."
1,SO2 ²,"{'Mean': -14.570361919149885, 'Std': 39.456202...","{'Mean': -12.97958142091824, 'Std': 35.4001882...","{'Mean': -16.335489798680847, 'Std': 43.712208...","{'Mean': -18.845538112648242, 'Std': 48.373346..."
2,SO2 ¹ + SO2 ²,"{'Mean': -18.529822311962157, 'Std': 39.157998...","{'Mean': -12.82624314241871, 'Std': 34.2589876...","{'Mean': -17.911487033417536, 'Std': 45.216400...","{'Mean': -18.56289373548618, 'Std': 46.2826940..."
3,SO2 ¹ + T,"{'Mean': -10.727288624179595, 'Std': 21.288727...","{'Mean': -7.132040011220129, 'Std': 14.4836227...","{'Mean': -10.971966446496706, 'Std': 22.279996...","{'Mean': -15.58718102824788, 'Std': 32.9128856..."
4,SO2 ² + T,"{'Mean': -8.942336426173204, 'Std': 20.7571085...","{'Mean': -10.498330202910287, 'Std': 23.962933...","{'Mean': -11.53925023710617, 'Std': 26.4633807...","{'Mean': -12.3675985279005, 'Std': 28.68341024..."
5,SO2 ¹ + SO2 ² + T,"{'Mean': -11.539383390863232, 'Std': 22.861836...","{'Mean': -10.511509631524714, 'Std': 23.910555...","{'Mean': -17.054700080305317, 'Std': 38.884107...","{'Mean': -12.439724292929743, 'Std': 28.954843..."

#### RMSE

In [138]:
so2_rmse_dataframe = (pd.read_csv(so2_rmse_file_name)
                .rename(columns={'Unnamed: 0': 'Sensores',
                                 'MLP Regression': 'MLP',
                                 'Multilinear Regression': 'MLR',
                                 'KNN Regression': 'KNN',
                                 'Random Forests Regression': 'RF'}))
so2_rmse_dataframe = so2_rmse_dataframe[~(so2_rmse_dataframe['Sensores'].str.contains("no Temp"))]
so2_rmse_dataframe['Sensores'] = (so2_rmse_dataframe['Sensores']
                            .apply(lambda names: rename_sensors_names(new_name='SO2', 
                                                                      old_names=names)))
so2_rmse_dataframe

,Sensores,MLP,MLR,KNN,RF
0,SO2 ¹,"{'Mean': -18.905160801571167, 'Std': 9.5593453...","{'Mean': -18.34426418722832, 'Std': 9.96872200...","{'Mean': -21.844364309601623, 'Std': 7.2341490...","{'Mean': -19.1973949811844, 'Std': 9.569110141..."
1,SO2 ²,"{'Mean': -18.593664927273434, 'Std': 8.7217964...","{'Mean': -18.056799140023166, 'Std': 8.9762249...","{'Mean': -18.952850976305445, 'Std': 8.1591401...","{'Mean': -20.23447673416731, 'Std': 7.76422604..."
2,SO2 ¹ + SO2 ²,"{'Mean': -22.400012425086352, 'Std': 9.2535353...","{'Mean': -18.159944525386727, 'Std': 8.8853787...","{'Mean': -19.583295205327893, 'Std': 7.4247449...","{'Mean': -20.024527690381532, 'Std': 7.6900385..."
3,SO2 ¹ + T,"{'Mean': -19.08386977096955, 'Std': 9.35785812...","{'Mean': -17.799630987481414, 'Std': 9.2904785...","{'Mean': -18.58881053188427, 'Std': 9.17374573...","{'Mean': -19.58379799399112, 'Std': 9.17310683..."
4,SO2 ² + T,"{'Mean': -18.89748757182596, 'Std': 9.50465549...","{'Mean': -17.97988990233685, 'Std': 8.86031122...","{'Mean': -19.355407550878994, 'Std': 9.1410786...","{'Mean': -19.375406007351003, 'Std': 8.8181342..."
5,SO2 ¹ + SO2 ² + T,"{'Mean': -19.185096594908366, 'Std': 9.0095284...","{'Mean': -18.069191820891838, 'Std': 8.8558514...","{'Mean': -20.08593115137528, 'Std': 8.91966870...","{'Mean': -19.07143017732373, 'Std': 8.95921346..."

#### MAE

In [139]:
so2_mae_dataframe = (pd.read_csv(so2_mae_file_name)
                .rename(columns={'Unnamed: 0': 'Sensores',
                                 'MLP Regression': 'MLP',
                                 'Multilinear Regression': 'MLR',
                                 'KNN Regression': 'KNN',
                                 'Random Forests Regression': 'RF'}))
so2_mae_dataframe = so2_mae_dataframe[~(so2_mae_dataframe['Sensores'].str.contains("no Temp"))]
so2_mae_dataframe['Sensores'] = (so2_mae_dataframe['Sensores']
                            .apply(lambda names: rename_sensors_names(new_name='SO2', 
                                                                      old_names=names)))
so2_mae_dataframe

,Sensores,MLP,MLR,KNN,RF
0,SO2 ¹,"{'Mean': -9.994121230727659, 'Std': 3.07222693...","{'Mean': -9.829478364605658, 'Std': 3.18184855...","{'Mean': -15.398580046920824, 'Std': 3.2990764...","{'Mean': -10.085065709413723, 'Std': 3.2479850..."
1,SO2 ²,"{'Mean': -9.227544365597513, 'Std': 3.45268139...","{'Mean': -9.365016712132862, 'Std': 3.16664132...","{'Mean': -9.296524884250474, 'Std': 3.28823560...","{'Mean': -9.517544183361078, 'Std': 3.05345767..."
2,SO2 ¹ + SO2 ²,"{'Mean': -10.53093613642009, 'Std': 4.02885542...","{'Mean': -9.36852785444277, 'Std': 3.120912758...","{'Mean': -9.192670621700879, 'Std': 2.86142848...","{'Mean': -9.254756087258787, 'Std': 2.96459598..."
3,SO2 ¹ + T,"{'Mean': -9.646254673850093, 'Std': 3.86741273...","{'Mean': -9.53493251797833, 'Std': 3.375572950...","{'Mean': -9.383631648387096, 'Std': 3.75065536...","{'Mean': -9.733812633168897, 'Std': 4.04944609..."
4,SO2 ² + T,"{'Mean': -9.065783913232073, 'Std': 3.83419948...","{'Mean': -9.607693466982074, 'Std': 2.93185846...","{'Mean': -9.372108645161289, 'Std': 3.86081850...","{'Mean': -9.227970950369654, 'Std': 3.74635176..."
5,SO2 ¹ + SO2 ² + T,"{'Mean': -8.945129945943943, 'Std': 4.00042585...","{'Mean': -9.606281439355524, 'Std': 2.95561926...","{'Mean': -9.222714133238773, 'Std': 3.98255633...","{'Mean': -9.189542619404875, 'Std': 3.86346350..."

## Performance metrics

### R2

In [159]:
import ast

r2_dataframe = pd.DataFrame(columns=['Sensores', 'MLP', 'MLR', 'KNN', 'RF'])
r2_original_dataframe = pd.concat([co_r2_dataframe, no2_r2_dataframe, o3_r2_dataframe, so2_r2_dataframe], axis=0)
r2_original_dataframe = r2_original_dataframe.reset_index().drop(columns='index')
r2_dataframe['Sensores'] = r2_original_dataframe['Sensores']
mask_dataframe = r2_dataframe.copy()
for index, row in r2_original_dataframe.iterrows():
    row_MLP = ast.literal_eval(row['MLP'])
    row_MLR = ast.literal_eval(row['MLR'])
    row_KNN = ast.literal_eval(row['KNN'])
    row_RF = ast.literal_eval(row['RF'])
    r2_dataframe.loc[index, 'MLP'] = f"{round(row_MLP['Mean'], 2)} ± {round(row_MLP['Std'], 2)}"
    r2_dataframe.loc[index, 'MLR'] = f"{round(row_MLR['Mean'], 2)} ± {round(row_MLR['Std'], 2)}"
    r2_dataframe.loc[index, 'KNN'] = f"{round(row_KNN['Mean'], 2)} ± {round(row_KNN['Std'], 2)}"
    r2_dataframe.loc[index, 'RF'] = f"{round(row_RF['Mean'], 2)} ± {round(row_RF['Std'], 2)}"
    
r2_dataframe

,Sensores,MLP,MLR,KNN,RF
0,CO,-0.47 ± 0.55,-0.52 ± 0.63,-0.61 ± 0.6,-0.63 ± 0.61
1,CO + T,-0.61 ± 0.48,-0.52 ± 0.61,-0.59 ± 0.42,-0.58 ± 0.49
2,NO2,-5.28 ± 7.52,-4.22 ± 6.15,-4.77 ± 6.47,-6.18 ± 8.36
3,NO2 + T,-2.8 ± 3.52,-4.25 ± 5.94,-2.92 ± 3.88,-3.39 ± 4.58
4,O3 ¹,-0.36 ± 0.49,-0.31 ± 0.39,-0.38 ± 0.38,-0.44 ± 0.54
5,O3 ²,0.11 ± 0.45,0.06 ± 0.51,0.03 ± 0.53,-0.03 ± 0.58
6,O3 ¹ + O3 ²,0.24 ± 0.29,0.11 ± 0.43,0.14 ± 0.35,0.17 ± 0.33
7,O3 ¹ + T,0.4 ± 0.29,0.32 ± 0.36,0.32 ± 0.32,0.34 ± 0.33
8,O3 ² + T,0.28 ± 0.58,0.33 ± 0.52,0.19 ± 0.8,0.27 ± 0.59
9,O3 ¹ + O3 ² + T,0.29 ± 0.54,0.32 ± 0.5,0.23 ± 0.66,0.28 ± 0.52
10,SO2 ¹,-8.71 ± 19.84,-6.94 ± 17.28,-31.96 ± 79.3,-11.78 ± 30.51
11,SO2 ²,-14.57 ± 39.46,-12.98 ± 35.4,-16.34 ± 43.71,-18.85 ± 48.37
12,SO2 ¹ + SO2 ²,-18.53 ± 39.16,-12.83 ± 34.26,-17.91 ± 45.22,-18.56 ± 46.28
13,SO2 ¹ + T,-10.73 ± 21.29,-7.13 ± 14.48,-10.97 ± 22.28,-15.59 ± 32.91
14,SO2 ² + T,-8.94 ± 20.76,-10.5 ± 23.96,-11.54 ± 26.46,-12.37 ± 28.68
15,SO2 ¹ + SO2 ² + T,-11.54 ± 22.86,-10.51 ± 23.91,-17.05 ± 38.88,-12.44 ± 28.95

### RMSE

In [161]:
import ast

rmse_dataframe = pd.DataFrame(columns=['Sensores', 'MLP', 'MLR', 'KNN', 'RF'])
rmse_original_dataframe = pd.concat([co_rmse_dataframe, no2_rmse_dataframe, o3_rmse_dataframe, so2_rmse_dataframe], axis=0)
rmse_original_dataframe = rmse_original_dataframe.reset_index().drop(columns='index')
rmse_dataframe['Sensores'] = rmse_original_dataframe['Sensores']
mask_dataframe = rmse_original_dataframe.copy()
for index, row in rmse_original_dataframe.iterrows():
    row_MLP = ast.literal_eval(row['MLP'])
    row_MLR = ast.literal_eval(row['MLR'])
    row_KNN = ast.literal_eval(row['KNN'])
    row_RF = ast.literal_eval(row['RF'])
    rmse_dataframe.loc[index, 'MLP'] = f"{round(row_MLP['Mean'], 2)} ± {round(row_MLP['Std'], 2)}"
    rmse_dataframe.loc[index, 'MLR'] = f"{round(row_MLR['Mean'], 2)} ± {round(row_MLR['Std'], 2)}"
    rmse_dataframe.loc[index, 'KNN'] = f"{round(row_KNN['Mean'], 2)} ± {round(row_KNN['Std'], 2)}"
    rmse_dataframe.loc[index, 'RF'] = f"{round(row_RF['Mean'], 2)} ± {round(row_RF['Std'], 2)}"
    
rmse_dataframe

,Sensores,MLP,MLR,KNN,RF
0,CO,-0.06 ± 0.02,-0.06 ± 0.02,-0.06 ± 0.02,-0.06 ± 0.02
1,CO + T,-0.06 ± 0.02,-0.06 ± 0.02,-0.06 ± 0.02,-0.06 ± 0.02
2,NO2,-13.18 ± 3.91,-12.84 ± 3.91,-13.09 ± 3.78,-14.14 ± 3.74
3,NO2 + T,-12.49 ± 3.77,-12.97 ± 3.66,-12.49 ± 3.76,-12.46 ± 3.51
4,O3 ¹,-16.16 ± 4.16,-16.08 ± 4.3,-16.54 ± 4.85,-16.49 ± 3.99
5,O3 ²,-12.76 ± 3.12,-13.07 ± 3.21,-13.13 ± 3.13,-13.54 ± 3.1
6,O3 ¹ + O3 ²,-11.84 ± 2.63,-12.7 ± 2.66,-12.58 ± 2.65,-12.41 ± 2.79
7,O3 ¹ + T,-10.55 ± 2.7,-11.04 ± 2.41,-11.21 ± 2.71,-11.08 ± 2.83
8,O3 ² + T,-11.24 ± 3.54,-10.84 ± 2.88,-11.58 ± 3.58,-11.32 ± 3.33
9,O3 ¹ + O3 ² + T,-11.1 ± 3.2,-10.82 ± 2.67,-11.35 ± 3.08,-11.23 ± 3.0
10,SO2 ¹,-18.91 ± 9.56,-18.34 ± 9.97,-21.84 ± 7.23,-19.2 ± 9.57
11,SO2 ²,-18.59 ± 8.72,-18.06 ± 8.98,-18.95 ± 8.16,-20.23 ± 7.76
12,SO2 ¹ + SO2 ²,-22.4 ± 9.25,-18.16 ± 8.89,-19.58 ± 7.42,-20.02 ± 7.69
13,SO2 ¹ + T,-19.08 ± 9.36,-17.8 ± 9.29,-18.59 ± 9.17,-19.58 ± 9.17
14,SO2 ² + T,-18.9 ± 9.5,-17.98 ± 8.86,-19.36 ± 9.14,-19.38 ± 8.82
15,SO2 ¹ + SO2 ² + T,-19.19 ± 9.01,-18.07 ± 8.86,-20.09 ± 8.92,-19.07 ± 8.96

### MAE

In [162]:
import ast

mae_dataframe = pd.DataFrame(columns=['Sensores', 'MLP', 'MLR', 'KNN', 'RF'])
mae_original_dataframe = pd.concat([co_mae_dataframe, no2_mae_dataframe, o3_mae_dataframe, so2_mae_dataframe], axis=0)
mae_original_dataframe = mae_original_dataframe.reset_index().drop(columns='index')
mae_dataframe['Sensores'] = mae_original_dataframe['Sensores']
mask_dataframe = mae_original_dataframe.copy()
for index, row in mae_original_dataframe.iterrows():
    row_MLP = ast.literal_eval(row['MLP'])
    row_MLR = ast.literal_eval(row['MLR'])
    row_KNN = ast.literal_eval(row['KNN'])
    row_RF = ast.literal_eval(row['RF'])
    mae_dataframe.loc[index, 'MLP'] = f"{round(row_MLP['Mean'], 2)} ± {round(row_MLP['Std'], 2)}"
    mae_dataframe.loc[index, 'MLR'] = f"{round(row_MLR['Mean'], 2)} ± {round(row_MLR['Std'], 2)}"
    mae_dataframe.loc[index, 'KNN'] = f"{round(row_KNN['Mean'], 2)} ± {round(row_KNN['Std'], 2)}"
    mae_dataframe.loc[index, 'RF'] = f"{round(row_RF['Mean'], 2)} ± {round(row_RF['Std'], 2)}"
    
mae_dataframe

,Sensores,MLP,MLR,KNN,RF
0,CO,-0.04 ± 0.02,-0.05 ± 0.01,-0.05 ± 0.01,-0.05 ± 0.01
1,CO + T,-0.05 ± 0.01,-0.05 ± 0.01,-0.05 ± 0.01,-0.05 ± 0.01
2,NO2,-10.21 ± 2.36,-9.9 ± 1.86,-10.09 ± 2.02,-10.8 ± 2.37
3,NO2 + T,-9.47 ± 2.17,-10.09 ± 1.81,-9.24 ± 2.03,-9.6 ± 2.09
4,O3 ¹,-12.85 ± 2.89,-12.77 ± 3.13,-12.74 ± 3.56,-13.12 ± 2.8
5,O3 ²,-10.21 ± 2.72,-10.43 ± 2.8,-10.52 ± 2.73,-10.82 ± 2.69
6,O3 ¹ + O3 ²,-9.18 ± 2.15,-9.97 ± 2.38,-9.84 ± 2.25,-9.72 ± 2.3
7,O3 ¹ + T,-8.21 ± 2.23,-8.73 ± 2.02,-8.64 ± 2.25,-8.58 ± 2.24
8,O3 ² + T,-8.8 ± 2.85,-8.67 ± 2.38,-9.27 ± 3.02,-9.07 ± 2.76
9,O3 ¹ + O3 ² + T,-8.68 ± 2.65,-8.64 ± 2.21,-8.88 ± 2.64,-8.85 ± 2.48
10,SO2 ¹,-9.99 ± 3.07,-9.83 ± 3.18,-15.4 ± 3.3,-10.09 ± 3.25
11,SO2 ²,-9.23 ± 3.45,-9.37 ± 3.17,-9.3 ± 3.29,-9.52 ± 3.05
12,SO2 ¹ + SO2 ²,-10.53 ± 4.03,-9.37 ± 3.12,-9.19 ± 2.86,-9.25 ± 2.96
13,SO2 ¹ + T,-9.65 ± 3.87,-9.53 ± 3.38,-9.38 ± 3.75,-9.73 ± 4.05
14,SO2 ² + T,-9.07 ± 3.83,-9.61 ± 2.93,-9.37 ± 3.86,-9.23 ± 3.75
15,SO2 ¹ + SO2 ² + T,-8.95 ± 4.0,-9.61 ± 2.96,-9.22 ± 3.98,-9.19 ± 3.86